newIssueWelcomeComment: >
  ğŸ‘‹ Thanks for opening your first issue here!

    We're glad to have you with us!

newPRWelcomeComment: >
  ğŸš€ Thanks for your PR, great to have you here!  
  
  Weâ€™ll review it shortly. Stay awesome! ğŸ’ª

firstPRMergeComment: >
  ğŸ‰ Your first PR is merged - welcome aboard!  
  
  Thanks for contributing, weâ€™d love to see you again. ğŸ’œ
